<?php

namespace Database\Seeders;

use App\Models\Accommodation;
use Illuminate\Database\Seeder;

class AccommodationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accommodations = [
            [
                'code' => 'ACC-BALI-001',
                'name' => 'Sunset Bay Resort Bali',
                'category' => 'resort',
                'star_rating' => 5,
                'location' => 'Nusa Dua',
                'city' => 'Badung',
                'province' => 'Bali',
                'address' => 'Jl. Pantai Sunset No. 12',
                'latitude' => -8.8123,
                'longitude' => 115.2331,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'contact_name' => 'Ayu Pramana',
                'contact_phone' => '+62 812-1000-1101',
                'contact_email' => 'reservation@sunsetbaybali.test',
                'website' => 'https://sunsetbaybali.test',
                'main_facilities' => 'Infinity pool, beach club, spa, gym, kids club',
                'description' => 'Beachfront resort ideal for family and honeymoon guests.',
                'cancellation_policy' => 'Free cancellation up to 7 days before check-in.',
                'notes' => 'High season surcharge applies for Jul-Aug and Dec.',
                'is_active' => true,
                'rooms' => [
                    [
                        'name' => 'Deluxe Garden Room',
                        'room_type' => 'Deluxe',
                        'bed_type' => 'King / Twin',
                        'view_type' => 'Garden',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 42,
                        'contract_rate' => 1350000,
                        'publish_rate' => 1750000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'WiFi, smart TV, minibar, rain shower',
                        'benefits' => 'Daily breakfast and welcome drink',
                        'is_refundable' => true,
                        'quantity_available' => 18,
                        'cancellation_policy' => 'Refundable up to 7 days',
                        'notes' => 'Connecting room on request',
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Premier Ocean Room',
                        'room_type' => 'Premier',
                        'bed_type' => 'King',
                        'view_type' => 'Ocean',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 48,
                        'contract_rate' => 1850000,
                        'publish_rate' => 2350000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'WiFi, balcony, bathtub, coffee machine',
                        'benefits' => 'Breakfast and one-time spa voucher',
                        'is_refundable' => true,
                        'quantity_available' => 12,
                        'cancellation_policy' => 'Refundable up to 7 days',
                        'notes' => 'Best for couples',
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Family Suite',
                        'room_type' => 'Suite',
                        'bed_type' => 'King + Twin',
                        'view_type' => 'Pool',
                        'max_occupancy' => 4,
                        'room_size_sqm' => 76,
                        'contract_rate' => 2650000,
                        'publish_rate' => 3300000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Living room, pantry, 2 bathrooms',
                        'benefits' => 'Breakfast and kids club access',
                        'is_refundable' => false,
                        'quantity_available' => 6,
                        'cancellation_policy' => 'Non-refundable',
                        'notes' => 'Extra bed available',
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Royal Beach Villa',
                        'room_type' => 'Villa',
                        'bed_type' => 'King',
                        'view_type' => 'Beachfront',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 120,
                        'contract_rate' => 5200000,
                        'publish_rate' => 6500000,
                        'currency' => 'IDR',
                        'meal_plan' => 'full_board',
                        'amenities' => 'Private pool, butler service, outdoor jacuzzi',
                        'benefits' => 'All meals, airport transfer',
                        'is_refundable' => false,
                        'quantity_available' => 3,
                        'cancellation_policy' => 'Non-refundable',
                        'notes' => 'Premium segment',
                        'is_active' => true,
                    ],
                ],
            ],
            [
                'code' => 'ACC-UBUD-002',
                'name' => 'Ubud Valley Eco Villa',
                'category' => 'villa',
                'star_rating' => 4,
                'location' => 'Ubud',
                'city' => 'Gianyar',
                'province' => 'Bali',
                'address' => 'Jl. Raya Tegalalang No. 88',
                'latitude' => -8.4595,
                'longitude' => 115.2792,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'contact_name' => 'Made Surya',
                'contact_phone' => '+62 813-2200-4402',
                'contact_email' => 'sales@ubudvalleyvilla.test',
                'website' => 'https://ubudvalleyvilla.test',
                'main_facilities' => 'Yoga deck, infinity pool, organic restaurant',
                'description' => 'Nature-focused villa with valley and rice terrace views.',
                'cancellation_policy' => 'Free cancellation up to 14 days before check-in.',
                'notes' => 'Popular for wellness retreat group.',
                'is_active' => true,
                'rooms' => [
                    [
                        'name' => 'Valley Suite',
                        'room_type' => 'Suite',
                        'bed_type' => 'King',
                        'view_type' => 'Valley',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 55,
                        'contract_rate' => 1450000,
                        'publish_rate' => 1900000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Bathtub, balcony, minibar',
                        'benefits' => 'Breakfast and daily afternoon tea',
                        'is_refundable' => true,
                        'quantity_available' => 10,
                        'cancellation_policy' => 'Refundable up to 14 days',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'River Pool Villa',
                        'room_type' => 'Villa',
                        'bed_type' => 'King',
                        'view_type' => 'River',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 98,
                        'contract_rate' => 2850000,
                        'publish_rate' => 3600000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Private pool, outdoor shower',
                        'benefits' => 'Breakfast and one complimentary yoga class',
                        'is_refundable' => false,
                        'quantity_available' => 5,
                        'cancellation_policy' => 'Non-refundable',
                        'notes' => 'Best-seller room category',
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Family Jungle Villa',
                        'room_type' => 'Villa',
                        'bed_type' => 'King + Twin',
                        'view_type' => 'Jungle',
                        'max_occupancy' => 4,
                        'room_size_sqm' => 115,
                        'contract_rate' => 3550000,
                        'publish_rate' => 4350000,
                        'currency' => 'IDR',
                        'meal_plan' => 'half_board',
                        'amenities' => '2 bedrooms, private deck',
                        'benefits' => 'Breakfast, dinner, and shuttle to Ubud center',
                        'is_refundable' => false,
                        'quantity_available' => 4,
                        'cancellation_policy' => 'Non-refundable',
                        'notes' => null,
                        'is_active' => true,
                    ],
                ],
            ],
            [
                'code' => 'ACC-LMBK-003',
                'name' => 'Lombok Seaside Hotel',
                'category' => 'hotel',
                'star_rating' => 4,
                'location' => 'Senggigi',
                'city' => 'Lombok Barat',
                'province' => 'Nusa Tenggara Barat',
                'address' => 'Jl. Raya Senggigi KM 7',
                'latitude' => -8.4921,
                'longitude' => 116.0438,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'contact_name' => 'Nia Hidayat',
                'contact_phone' => '+62 811-7700-3303',
                'contact_email' => 'reservation@lombokseaside.test',
                'website' => 'https://lombokseaside.test',
                'main_facilities' => 'Pool, beachfront restaurant, meeting room',
                'description' => 'Comfortable beachfront hotel for leisure and incentive groups.',
                'cancellation_policy' => 'Free cancellation up to 10 days before check-in.',
                'notes' => null,
                'is_active' => true,
                'rooms' => [
                    [
                        'name' => 'Superior Room',
                        'room_type' => 'Superior',
                        'bed_type' => 'Twin',
                        'view_type' => 'Garden',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 32,
                        'contract_rate' => 950000,
                        'publish_rate' => 1250000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'WiFi, shower, work desk',
                        'benefits' => 'Breakfast buffet',
                        'is_refundable' => true,
                        'quantity_available' => 20,
                        'cancellation_policy' => 'Refundable up to 10 days',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Deluxe Sea View',
                        'room_type' => 'Deluxe',
                        'bed_type' => 'King',
                        'view_type' => 'Sea',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 40,
                        'contract_rate' => 1300000,
                        'publish_rate' => 1690000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Balcony, smart TV, bathtub',
                        'benefits' => 'Breakfast and 10% F&B discount',
                        'is_refundable' => true,
                        'quantity_available' => 14,
                        'cancellation_policy' => 'Refundable up to 10 days',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Junior Suite',
                        'room_type' => 'Suite',
                        'bed_type' => 'King',
                        'view_type' => 'Sea',
                        'max_occupancy' => 3,
                        'room_size_sqm' => 58,
                        'contract_rate' => 1950000,
                        'publish_rate' => 2450000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Living area, pantry, bathtub',
                        'benefits' => 'Breakfast and airport pickup',
                        'is_refundable' => false,
                        'quantity_available' => 6,
                        'cancellation_policy' => 'Non-refundable',
                        'notes' => null,
                        'is_active' => true,
                    ],
                ],
            ],
            [
                'code' => 'ACC-JKT-004',
                'name' => 'Metropolitan Grand Jakarta',
                'category' => 'hotel',
                'star_rating' => 5,
                'location' => 'Sudirman',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'address' => 'Jl. Jend. Sudirman Kav. 55',
                'latitude' => -6.2231,
                'longitude' => 106.8077,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'contact_name' => 'Rizki Amalia',
                'contact_phone' => '+62 811-9000-1212',
                'contact_email' => 'sales@metrograndjakarta.test',
                'website' => 'https://metrograndjakarta.test',
                'main_facilities' => 'Ballroom, gym, lounge, airport transfer desk',
                'description' => 'Business city hotel with excellent meeting facilities.',
                'cancellation_policy' => 'Free cancellation up to 3 days before check-in.',
                'notes' => 'Contract includes corporate weekday rates.',
                'is_active' => true,
                'rooms' => [
                    [
                        'name' => 'Business Deluxe',
                        'room_type' => 'Deluxe',
                        'bed_type' => 'King / Twin',
                        'view_type' => 'City',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 36,
                        'contract_rate' => 1550000,
                        'publish_rate' => 2100000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Work desk, WiFi, coffee machine',
                        'benefits' => 'Breakfast and daily laundry (2 pcs)',
                        'is_refundable' => true,
                        'quantity_available' => 35,
                        'cancellation_policy' => 'Refundable up to 3 days',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Executive Club',
                        'room_type' => 'Executive',
                        'bed_type' => 'King',
                        'view_type' => 'City',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 42,
                        'contract_rate' => 2100000,
                        'publish_rate' => 2800000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Club lounge access, bathtub',
                        'benefits' => 'Breakfast, evening cocktail, meeting room 2 hours',
                        'is_refundable' => true,
                        'quantity_available' => 20,
                        'cancellation_policy' => 'Refundable up to 3 days',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Premier Suite',
                        'room_type' => 'Suite',
                        'bed_type' => 'King',
                        'view_type' => 'City Skyline',
                        'max_occupancy' => 3,
                        'room_size_sqm' => 72,
                        'contract_rate' => 3400000,
                        'publish_rate' => 4300000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Living room, pantry, bathtub',
                        'benefits' => 'Breakfast, lounge access, airport drop',
                        'is_refundable' => false,
                        'quantity_available' => 8,
                        'cancellation_policy' => 'Non-refundable',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Family Connected Room',
                        'room_type' => 'Family',
                        'bed_type' => 'King + Twin',
                        'view_type' => 'City',
                        'max_occupancy' => 4,
                        'room_size_sqm' => 70,
                        'contract_rate' => 2950000,
                        'publish_rate' => 3600000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Connecting room, 2 bathrooms',
                        'benefits' => 'Breakfast and kids welcome amenities',
                        'is_refundable' => false,
                        'quantity_available' => 6,
                        'cancellation_policy' => 'Non-refundable',
                        'notes' => null,
                        'is_active' => true,
                    ],
                ],
            ],
            [
                'code' => 'ACC-LABN-005',
                'name' => 'Komodo Cliff Boutique Resort',
                'category' => 'boutique_hotel',
                'star_rating' => 4,
                'location' => 'Labuan Bajo',
                'city' => 'Manggarai Barat',
                'province' => 'Nusa Tenggara Timur',
                'address' => 'Jl. Pantai Pede No. 5',
                'latitude' => -8.4969,
                'longitude' => 119.8871,
                'check_in_time' => '14:00',
                'check_out_time' => '11:00',
                'contact_name' => 'Ferdy Gaspersz',
                'contact_phone' => '+62 811-6600-9988',
                'contact_email' => 'booking@komodocliff.test',
                'website' => 'https://komodocliff.test',
                'main_facilities' => 'Sunset deck, infinity pool, diving desk',
                'description' => 'Boutique cliffside resort for Komodo island experience.',
                'cancellation_policy' => 'Free cancellation up to 5 days before check-in.',
                'notes' => 'Boat charter add-on available through partner.',
                'is_active' => true,
                'rooms' => [
                    [
                        'name' => 'Cliff Deluxe',
                        'room_type' => 'Deluxe',
                        'bed_type' => 'King',
                        'view_type' => 'Sea',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 38,
                        'contract_rate' => 1425000,
                        'publish_rate' => 1850000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Balcony, smart TV, rain shower',
                        'benefits' => 'Breakfast and sunset tea',
                        'is_refundable' => true,
                        'quantity_available' => 11,
                        'cancellation_policy' => 'Refundable up to 5 days',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Ocean Loft',
                        'room_type' => 'Loft',
                        'bed_type' => 'King',
                        'view_type' => 'Ocean',
                        'max_occupancy' => 3,
                        'room_size_sqm' => 60,
                        'contract_rate' => 2250000,
                        'publish_rate' => 2900000,
                        'currency' => 'IDR',
                        'meal_plan' => 'breakfast',
                        'amenities' => 'Loft living area, coffee machine',
                        'benefits' => 'Breakfast and one-way harbor transfer',
                        'is_refundable' => false,
                        'quantity_available' => 5,
                        'cancellation_policy' => 'Non-refundable',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Sunset Suite',
                        'room_type' => 'Suite',
                        'bed_type' => 'King',
                        'view_type' => 'Sunset Bay',
                        'max_occupancy' => 2,
                        'room_size_sqm' => 72,
                        'contract_rate' => 2950000,
                        'publish_rate' => 3700000,
                        'currency' => 'IDR',
                        'meal_plan' => 'half_board',
                        'amenities' => 'Private deck, bathtub',
                        'benefits' => 'Breakfast + dinner and priority sunset seat',
                        'is_refundable' => false,
                        'quantity_available' => 4,
                        'cancellation_policy' => 'Non-refundable',
                        'notes' => null,
                        'is_active' => true,
                    ],
                ],
            ],
        ];

        foreach ($accommodations as $row) {
            $rooms = $row['rooms'];
            unset($row['rooms']);

            $accommodation = Accommodation::query()->updateOrCreate(
                ['code' => $row['code']],
                array_merge([
                    'gallery_images' => [],
                ], $row)
            );

            $accommodation->rooms()->delete();
            $accommodation->rooms()->createMany($rooms);
        }
    }
}

