<?php

namespace Database\Seeders;

use App\Models\Transport;
use Illuminate\Database\Seeder;

class TransportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $transports = [
            [
                'code' => 'TRN-BALI-001',
                'name' => 'Bali Premium Land Transfer',
                'transport_type' => 'car',
                'provider_name' => 'PT Bali Mobility Nusantara',
                'service_scope' => 'airport_transfer',
                'location' => 'Kuta',
                'city' => 'Badung',
                'province' => 'Bali',
                'contact_name' => 'Kadek Pramana',
                'contact_phone' => '+62 812-3000-1101',
                'contact_email' => 'sales@balimobility.test',
                'website' => 'https://balimobility.test',
                'description' => 'Airport and hotel transfers with professional drivers.',
                'inclusions' => 'Driver, fuel, parking fee in destination area',
                'exclusions' => 'Toll, entrance tickets, overtime (if any)',
                'cancellation_policy' => 'Free cancellation up to 24 hours before pickup.',
                'notes' => 'Peak season surcharge applies in Jul-Aug and year-end.',
                'is_active' => true,
                'units' => [
                    [
                        'name' => 'Toyota Avanza',
                        'vehicle_type' => 'MPV',
                        'brand_model' => 'Toyota Avanza 1.5 G',
                        'seat_capacity' => 5,
                        'luggage_capacity' => 3,
                        'contract_rate' => 550000,
                        'publish_rate' => 700000,
                        'overtime_rate' => 75000,
                        'currency' => 'IDR',
                        'fuel_type' => 'petrol',
                        'transmission' => 'automatic',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Mineral water and sanitizer',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Toyota Innova Zenix',
                        'vehicle_type' => 'MPV',
                        'brand_model' => 'Toyota Innova Zenix Hybrid',
                        'seat_capacity' => 6,
                        'luggage_capacity' => 4,
                        'contract_rate' => 850000,
                        'publish_rate' => 1050000,
                        'overtime_rate' => 100000,
                        'currency' => 'IDR',
                        'fuel_type' => 'hybrid',
                        'transmission' => 'automatic',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Mineral water and airport meet & greet',
                        'notes' => 'Suitable for executive guests',
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Toyota Alphard',
                        'vehicle_type' => 'Luxury MPV',
                        'brand_model' => 'Toyota Alphard 2.5',
                        'seat_capacity' => 5,
                        'luggage_capacity' => 3,
                        'contract_rate' => 1850000,
                        'publish_rate' => 2300000,
                        'overtime_rate' => 175000,
                        'currency' => 'IDR',
                        'fuel_type' => 'petrol',
                        'transmission' => 'automatic',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Meet & greet and premium amenities',
                        'notes' => null,
                        'is_active' => true,
                    ],
                ],
            ],
            [
                'code' => 'TRN-BALI-002',
                'name' => 'Bali Group Coach Services',
                'transport_type' => 'bus',
                'provider_name' => 'PT Dewata Coach Line',
                'service_scope' => 'daily_tour',
                'location' => 'Denpasar',
                'city' => 'Denpasar',
                'province' => 'Bali',
                'contact_name' => 'Komang Arya',
                'contact_phone' => '+62 813-7000-2202',
                'contact_email' => 'operation@dewatacoach.test',
                'website' => 'https://dewatacoach.test',
                'description' => 'Daily city tour and intercity transfer for group series.',
                'inclusions' => 'Driver, fuel, parking, basic insurance',
                'exclusions' => 'Toll, meals, local levy',
                'cancellation_policy' => 'Free cancellation up to 48 hours before departure.',
                'notes' => 'Weekend allocation needs reconfirmation H-2.',
                'is_active' => true,
                'units' => [
                    [
                        'name' => 'Medium Bus 31 Seats',
                        'vehicle_type' => 'Bus',
                        'brand_model' => 'Hino RK8',
                        'seat_capacity' => 31,
                        'luggage_capacity' => 25,
                        'contract_rate' => 2200000,
                        'publish_rate' => 2750000,
                        'overtime_rate' => 225000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Mic and cool box',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Big Bus 45 Seats',
                        'vehicle_type' => 'Bus',
                        'brand_model' => 'Mercedes OH 1626',
                        'seat_capacity' => 45,
                        'luggage_capacity' => 35,
                        'contract_rate' => 3200000,
                        'publish_rate' => 3900000,
                        'overtime_rate' => 300000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Mic and charging port',
                        'notes' => 'Best for MICE groups',
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Hiace Commuter',
                        'vehicle_type' => 'Minibus',
                        'brand_model' => 'Toyota Hiace Commuter',
                        'seat_capacity' => 14,
                        'luggage_capacity' => 8,
                        'contract_rate' => 1400000,
                        'publish_rate' => 1750000,
                        'overtime_rate' => 125000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Mineral water',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Hiace Premio',
                        'vehicle_type' => 'Minibus',
                        'brand_model' => 'Toyota Hiace Premio',
                        'seat_capacity' => 12,
                        'luggage_capacity' => 8,
                        'contract_rate' => 1650000,
                        'publish_rate' => 2000000,
                        'overtime_rate' => 150000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Mineral water and basic first-aid kit',
                        'notes' => 'Comfort-focused option',
                        'is_active' => true,
                    ],
                ],
            ],
            [
                'code' => 'TRN-LMBK-003',
                'name' => 'Lombok Island Transfer',
                'transport_type' => 'van',
                'provider_name' => 'CV Sasak Transport',
                'service_scope' => 'intercity',
                'location' => 'Mataram',
                'city' => 'Mataram',
                'province' => 'Nusa Tenggara Barat',
                'contact_name' => 'Ilham Rasyid',
                'contact_phone' => '+62 812-8800-3303',
                'contact_email' => 'booking@sasaktransport.test',
                'website' => 'https://sasaktransport.test',
                'description' => 'Intercity transfer and point-to-point service across Lombok.',
                'inclusions' => 'Driver, fuel',
                'exclusions' => 'Harbor fee and toll',
                'cancellation_policy' => 'Free cancellation up to 24 hours before pickup.',
                'notes' => null,
                'is_active' => true,
                'units' => [
                    [
                        'name' => 'Suzuki APV',
                        'vehicle_type' => 'Van',
                        'brand_model' => 'Suzuki APV GX',
                        'seat_capacity' => 7,
                        'luggage_capacity' => 4,
                        'contract_rate' => 780000,
                        'publish_rate' => 980000,
                        'overtime_rate' => 90000,
                        'currency' => 'IDR',
                        'fuel_type' => 'petrol',
                        'transmission' => 'manual',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Mineral water',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Isuzu Elf Short',
                        'vehicle_type' => 'Minibus',
                        'brand_model' => 'Isuzu Elf NLR',
                        'seat_capacity' => 16,
                        'luggage_capacity' => 10,
                        'contract_rate' => 1550000,
                        'publish_rate' => 1900000,
                        'overtime_rate' => 145000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Driver and helper',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Isuzu Elf Long',
                        'vehicle_type' => 'Minibus',
                        'brand_model' => 'Isuzu Elf Long Chassis',
                        'seat_capacity' => 19,
                        'luggage_capacity' => 12,
                        'contract_rate' => 1800000,
                        'publish_rate' => 2200000,
                        'overtime_rate' => 165000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Driver and helper',
                        'notes' => 'Preferred for island overland tours',
                        'is_active' => true,
                    ],
                ],
            ],
            [
                'code' => 'TRN-JKT-004',
                'name' => 'Jakarta Executive Mobility',
                'transport_type' => 'car',
                'provider_name' => 'PT Metro Executive Fleet',
                'service_scope' => 'charter',
                'location' => 'Sudirman',
                'city' => 'Jakarta Selatan',
                'province' => 'DKI Jakarta',
                'contact_name' => 'Nadia Putri',
                'contact_phone' => '+62 811-9200-4404',
                'contact_email' => 'corporate@metrofleet.test',
                'website' => 'https://metrofleet.test',
                'description' => 'Corporate charter with premium fleet and trained chauffeurs.',
                'inclusions' => 'Driver, fuel, parking',
                'exclusions' => 'Toll and overtime',
                'cancellation_policy' => 'Free cancellation up to 12 hours before pickup.',
                'notes' => 'Best for executive movement and business visits.',
                'is_active' => true,
                'units' => [
                    [
                        'name' => 'Toyota Camry',
                        'vehicle_type' => 'Sedan',
                        'brand_model' => 'Toyota Camry 2.5 V',
                        'seat_capacity' => 3,
                        'luggage_capacity' => 2,
                        'contract_rate' => 1600000,
                        'publish_rate' => 2000000,
                        'overtime_rate' => 165000,
                        'currency' => 'IDR',
                        'fuel_type' => 'petrol',
                        'transmission' => 'automatic',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Complimentary wifi and bottled water',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Toyota Fortuner',
                        'vehicle_type' => 'SUV',
                        'brand_model' => 'Toyota Fortuner VRZ',
                        'seat_capacity' => 5,
                        'luggage_capacity' => 4,
                        'contract_rate' => 1800000,
                        'publish_rate' => 2250000,
                        'overtime_rate' => 185000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'automatic',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Complimentary wifi and bottled water',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Hyundai Ioniq 5',
                        'vehicle_type' => 'EV',
                        'brand_model' => 'Hyundai Ioniq 5 Signature',
                        'seat_capacity' => 4,
                        'luggage_capacity' => 3,
                        'contract_rate' => 1750000,
                        'publish_rate' => 2200000,
                        'overtime_rate' => 180000,
                        'currency' => 'IDR',
                        'fuel_type' => 'electric',
                        'transmission' => 'automatic',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Green mobility package',
                        'notes' => 'Charging cost included within city usage',
                        'is_active' => true,
                    ],
                ],
            ],
            [
                'code' => 'TRN-LABN-005',
                'name' => 'Labuan Bajo Sea Transfer',
                'transport_type' => 'boat',
                'provider_name' => 'PT Komodo Marine Charter',
                'service_scope' => 'daily_tour',
                'location' => 'Labuan Bajo',
                'city' => 'Manggarai Barat',
                'province' => 'Nusa Tenggara Timur',
                'contact_name' => 'Yohanes Laga',
                'contact_phone' => '+62 812-7700-5505',
                'contact_email' => 'booking@komodomarine.test',
                'website' => 'https://komodomarine.test',
                'description' => 'Fast boat and phinisi options for island hopping.',
                'inclusions' => 'Captain and crew',
                'exclusions' => 'Harbor fee, park entry, meal package',
                'cancellation_policy' => 'Free cancellation up to 72 hours before departure.',
                'notes' => 'Weather-dependent operation policy applies.',
                'is_active' => true,
                'units' => [
                    [
                        'name' => 'Fast Boat 15 Pax',
                        'vehicle_type' => 'Speedboat',
                        'brand_model' => 'Yamaha Twin Engine 250HP',
                        'seat_capacity' => 15,
                        'luggage_capacity' => 10,
                        'contract_rate' => 4800000,
                        'publish_rate' => 5900000,
                        'overtime_rate' => 450000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => false,
                        'with_driver' => true,
                        'benefits' => 'Crew and life jackets',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Fast Boat 25 Pax',
                        'vehicle_type' => 'Speedboat',
                        'brand_model' => 'Yamaha Triple Engine 300HP',
                        'seat_capacity' => 25,
                        'luggage_capacity' => 15,
                        'contract_rate' => 6900000,
                        'publish_rate' => 8400000,
                        'overtime_rate' => 650000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => false,
                        'with_driver' => true,
                        'benefits' => 'Crew and life jackets',
                        'notes' => null,
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Phinisi Day Cruise',
                        'vehicle_type' => 'Phinisi',
                        'brand_model' => 'Luxury Phinisi 8 Cabins',
                        'seat_capacity' => 20,
                        'luggage_capacity' => 20,
                        'contract_rate' => 14500000,
                        'publish_rate' => 17500000,
                        'overtime_rate' => 1200000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => true,
                        'with_driver' => true,
                        'benefits' => 'Captain, crew, snorkel gear',
                        'notes' => 'Premium island hopping package',
                        'is_active' => true,
                    ],
                    [
                        'name' => 'Open Deck Boat 10 Pax',
                        'vehicle_type' => 'Wooden Boat',
                        'brand_model' => 'Traditional Open Deck',
                        'seat_capacity' => 10,
                        'luggage_capacity' => 6,
                        'contract_rate' => 2600000,
                        'publish_rate' => 3200000,
                        'overtime_rate' => 250000,
                        'currency' => 'IDR',
                        'fuel_type' => 'diesel',
                        'transmission' => 'manual',
                        'air_conditioned' => false,
                        'with_driver' => true,
                        'benefits' => 'Crew and safety equipment',
                        'notes' => 'Budget-friendly option',
                        'is_active' => true,
                    ],
                ],
            ],
        ];

        foreach ($transports as $data) {
            $units = $data['units'];
            unset($data['units']);

            $transport = Transport::query()->updateOrCreate(
                ['code' => $data['code']],
                $data
            );

            $transport->units()->delete();
            $transport->units()->createMany($units);
        }
    }
}
