@extends('layouts.master')

@section('content')
    <div class="space-y-6">
        <div class="flex items-center justify-between">
            <div>
                <h1 class="text-2xl font-semibold text-gray-800 dark:text-gray-100">Invoice Detail</h1>
                <p class="mt-1 text-sm text-gray-600 dark:text-gray-300">{{ $invoice->invoice_number }}</p>
            </div>
            <a href="{{ route('invoices.index') }}" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:text-gray-200 dark:hover:bg-gray-700">
                Back
            </a>
        </div>

        <div class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800">
            <dl class="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Invoice Number</dt><dd class="text-sm font-medium text-gray-800 dark:text-gray-100">{{ $invoice->invoice_number }}</dd></div>
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Status</dt><dd class="text-sm"><x-status-badge :status="$invoice->status" size="xs" /></dd></div>
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Booking</dt><dd class="text-sm text-gray-800 dark:text-gray-100">{{ $invoice->booking->booking_number ?? '-' }}</dd></div>
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Quotation</dt><dd class="text-sm text-gray-800 dark:text-gray-100">{{ $invoice->booking->quotation->quotation_number ?? '-' }}</dd></div>
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Customer</dt><dd class="text-sm text-gray-800 dark:text-gray-100">{{ $invoice->booking->quotation->inquiry->customer->name ?? '-' }}</dd></div>
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Amount</dt><dd class="text-sm text-gray-800 dark:text-gray-100">Rp {{ number_format($invoice->total_amount ?? 0, 2, ',', '.') }}</dd></div>
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Invoice Date</dt><dd class="text-sm text-gray-800 dark:text-gray-100">{{ $invoice->invoice_date?->format('Y-m-d') ?? '-' }}</dd></div>
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Due Date</dt><dd class="text-sm text-gray-800 dark:text-gray-100">{{ $invoice->due_date?->format('Y-m-d') ?? '-' }}</dd></div>
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Generated By</dt><dd class="text-sm text-gray-800 dark:text-gray-100">{{ $invoice->generatedBy->name ?? '-' }}</dd></div>
                <div><dt class="text-xs text-gray-500 dark:text-gray-400">Paid At</dt><dd class="text-sm text-gray-800 dark:text-gray-100">{{ $invoice->paid_at?->format('Y-m-d H:i') ?? '-' }}</dd></div>
            </dl>
        </div>
    </div>
@endsection


