<?php

return [
    'inquiry' => [
        'options' => [
            'new_request','need_customer_data','registered','assigned','contacted','waiting_customer','qualified','unqualified','itinerary_in_progress','quotation_in_progress','quotation_sent','under_negotiation','accepted','converted_to_booking','lost','cancelled','expired',
        ],
        'terminal' => ['converted_to_booking','lost','cancelled','expired','unqualified'],
        'default' => 'new_request',
        'legacy_map' => [
            'new' => 'new_request',
            'follow_up' => 'contacted',
            'quoted' => 'quotation_in_progress',
            'converted' => 'converted_to_booking',
            'closed' => 'lost',
            'draft' => 'new_request',
            'processed' => 'contacted',
            'pending' => 'qualified',
            'approved' => 'accepted',
            'rejected' => 'lost',
            'final' => 'converted_to_booking',
        ],
    ],
    'itinerary' => [
        'options' => [
            'draft','in_review','approved','quotation_generated','revised','confirmed','converted_to_booking','cancelled','archived',
        ],
        'terminal' => ['converted_to_booking','cancelled','archived'],
        'default' => 'draft',
        'legacy_map' => [
            'pending' => 'draft',
            'processed' => 'quotation_generated',
            'final' => 'converted_to_booking',
            'approved' => 'approved',
            'rejected' => 'cancelled',
            'draft' => 'draft',
        ],
    ],
    'quotation' => [
        'options' => [
            'draft','pending_validation','validated','sent','revision_requested','revised','accepted','rejected','expired','converted','superseded','amended','cancelled',
        ],
        'terminal' => ['converted','cancelled','superseded','expired','rejected'],
        'bookable' => ['accepted','converted'],
        'default' => 'draft',
        'legacy_map' => [
            'draft' => 'draft',
            'pending' => 'pending_validation',
            'processed' => 'revised',
            'sent' => 'sent',
            'approved' => 'accepted',
            'rejected' => 'rejected',
            'final' => 'converted',
        ],
    ],
    'booking' => [
        'options' => [
            'pending_confirmation','confirmed','awaiting_dp','dp_received','awaiting_balance','ready_to_operate','in_operation','service_completed','completed_unsettled','completed_settled','closed','cancelled',
        ],
        'terminal' => ['closed','cancelled'],
        'default' => 'pending_confirmation',
        'legacy_map' => [
            'draft' => 'pending_confirmation',
            'processed' => 'confirmed',
            'pending' => 'awaiting_dp',
            'approved' => 'ready_to_operate',
            'rejected' => 'cancelled',
            'final' => 'closed',
            'confirmed' => 'confirmed',
            'completed' => 'closed',
            'cancelled' => 'cancelled',
        ],
    ],
    'invoice' => [
        'options' => [
            'draft','issued','partially_paid','paid','overpaid','revised','void','cancelled',
        ],
        'terminal' => ['paid','void','cancelled'],
        'default' => 'draft',
        'legacy_map' => [
            'issued' => 'issued',
            'paid' => 'paid',
            'void' => 'void',
            'draft' => 'draft',
            'processed' => 'issued',
            'pending' => 'issued',
            'approved' => 'paid',
            'rejected' => 'void',
            'final' => 'paid',
        ],
    ],
    'payment' => [
        'options' => [
            'pending','waiting_confirmation','confirmed','rejected','cancelled','refunded','allocated_as_deposit',
        ],
        'default' => 'pending',
    ],
    'booking_settlement' => [
        'options' => [
            'pending_review',
            'outstanding_balance',
            'pending_payment',
            'pending_adjustment',
            'overpaid',
            'refund_required',
            'deposit_recorded',
            'settled',
            'closed_blocked',
        ],
        'default' => 'pending_review',
    ],
    'booking_adjustment' => [
        'options' => [
            'draft', 'pending_approval', 'approved', 'rejected', 'applied', 'cancelled',
        ],
        'default' => 'draft',
    ],
    'badge_classes' => [
        'default' => 'bg-slate-100 text-slate-600 border-slate-200 dark:bg-slate-800 dark:text-slate-200 dark:border-slate-700',
        'new_request' => 'bg-blue-100 text-blue-700 border-blue-200 dark:bg-blue-900/40 dark:text-blue-800 dark:border-blue-800',
        'need_customer_data' => 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/40 dark:text-amber-200 dark:border-amber-800',
        'waiting_customer' => 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/40 dark:text-amber-200 dark:border-amber-800',
        'qualified' => 'bg-sky-100 text-sky-700 border-sky-200 dark:bg-sky-900/40 dark:text-sky-200 dark:border-sky-800',
        'unqualified' => 'bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:border-rose-800',
        'pending_validation' => 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/40 dark:text-amber-200 dark:border-amber-800',
        'validated' => 'bg-cyan-100 text-cyan-700 border-cyan-200 dark:bg-cyan-900/40 dark:text-cyan-200 dark:border-cyan-800',
        'pending_approval' => 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/40 dark:text-amber-200 dark:border-amber-800',
        'approved' => 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/40 dark:text-emerald-200 dark:border-emerald-800',
        'applied' => 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/40 dark:text-emerald-200 dark:border-emerald-800',
        'sent' => 'bg-indigo-100 text-indigo-700 border-indigo-200 dark:bg-indigo-900/40 dark:text-indigo-200 dark:border-indigo-800',
        'accepted' => 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/40 dark:text-emerald-200 dark:border-emerald-800',
        'converted' => 'bg-violet-100 text-violet-700 border-violet-200 dark:bg-violet-900/40 dark:text-violet-200 dark:border-violet-800',
        'converted_to_booking' => 'bg-violet-100 text-violet-700 border-violet-200 dark:bg-violet-900/40 dark:text-violet-200 dark:border-violet-800',
        'cancelled' => 'bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:border-rose-800',
        'rejected' => 'bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:border-rose-800',
        'expired' => 'bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:border-rose-800',
        'closed' => 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/40 dark:text-emerald-200 dark:border-emerald-800',
        'pending_review' => 'bg-sky-100 text-sky-700 border-sky-200 dark:bg-sky-900/40 dark:text-sky-200 dark:border-sky-800',
        'outstanding_balance' => 'bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:border-rose-800',
        'pending_payment' => 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/40 dark:text-amber-200 dark:border-amber-800',
        'pending_adjustment' => 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/40 dark:text-amber-200 dark:border-amber-800',
        'overpaid' => 'bg-violet-100 text-violet-700 border-violet-200 dark:bg-violet-900/40 dark:text-violet-200 dark:border-violet-800',
        'refund_required' => 'bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:border-rose-800',
        'deposit_recorded' => 'bg-cyan-100 text-cyan-700 border-cyan-200 dark:bg-cyan-900/40 dark:text-cyan-200 dark:border-cyan-800',
        'settled' => 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/40 dark:text-emerald-200 dark:border-emerald-800',
        'closed_blocked' => 'bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:border-rose-800',
        'refunded' => 'bg-cyan-100 text-cyan-700 border-cyan-200 dark:bg-cyan-900/40 dark:text-cyan-200 dark:border-cyan-800',
        'allocated_as_deposit' => 'bg-indigo-100 text-indigo-700 border-indigo-200 dark:bg-indigo-900/40 dark:text-indigo-200 dark:border-indigo-800',
        'active' => 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/40 dark:text-emerald-200 dark:border-emerald-800',
        'inactive' => 'bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/40 dark:text-rose-200 dark:border-rose-800',
    ],
];
