<?php
$base = getcwd();
$targets = [
  'zh_Hant' => $base.'/lang/zh_Hant/ui_core.php',
  'zh_Hans' => $base.'/lang/zh_Hans/ui_core.php',
];

$maps = [
  'zh_Hant' => [
    'Create New Password'=>'建立新密碼','Reset Password'=>'重設密碼','Welcome Back'=>'歡迎回來','Back to Sign In'=>'返回登入','Confirm New Password'=>'確認新密碼','Email Address'=>'電子郵件','Forgot Password?'=>'忘記密碼？','Loading...'=>'載入中...','New Password'=>'新密碼','Password'=>'密碼','Remember me'=>'記住我','Send Reset Link'=>'發送重設連結','Sending Link...'=>'發送中...','Sign In'=>'登入','Signing In...'=>'登入中...','Update Password'=>'更新密碼','Processing...'=>'處理中...','Forgot Password'=>'忘記密碼','Login'=>'登入','Set New Password'=>'設定新密碼',
    'Actions'=>'操作','Activate'=>'啟用','Active'=>'啟用','Activity Timeline'=>'活動時間軸','Add History'=>'新增紀錄','Add Reminder'=>'新增提醒','Adult'=>'成人','All Days'=>'全部天數','All Destinations'=>'全部目的地','All Status'=>'全部狀態','All Types'=>'全部類型','All Vendors'=>'全部供應商','Amount'=>'金額','Approval'=>'審批','Approval Log'=>'審批紀錄','Approve'=>'核准','Assigned'=>'已指派','Audit Info'=>'審計資訊','Back'=>'返回','Benefits'=>'優勢','Booking'=>'預訂','Booking Number'=>'預訂編號','Cancel'=>'取消','Cancellation Policy'=>'取消政策','Capacity'=>'容量','Channel'=>'渠道','Child'=>'兒童','Clone'=>'複製','Close'=>'關閉','Communication History'=>'溝通紀錄','Confirm Reject'=>'確認拒絕','Contact At'=>'聯絡時間','Country'=>'國家','Created'=>'已建立','Created At'=>'建立時間','Created By'=>'建立者','Customer'=>'客戶','Deactivate'=>'停用','Deadline'=>'截止日','Default'=>'預設','Delete'=>'刪除','Description'=>'說明','Destination'=>'目的地','Detail'=>'詳情','Disabled'=>'停用','Discount'=>'折扣','Discount Type'=>'折扣類型','Discount Value'=>'折扣值','Done'=>'完成','Download PDF'=>'下載 PDF','Duplicate'=>'複製','Duration'=>'天數','Edit'=>'編輯','Enabled'=>'啟用','End'=>'結束','End Point'=>'終點','Excludes'=>'不含','Filters'=>'篩選','Final Amount'=>'最終金額','Fixed'=>'固定','Follow-up'=>'跟進','From Date'=>'起始日期','Gallery'=>'圖庫','Generate Quotation'=>'產生報價單','Generated By'=>'產生者','Global Discount'=>'全域折扣','Guidelines'=>'指引','Inactive'=>'停用','Includes'=>'包含','Info'=>'資訊','Inquiry'=>'詢價','Inquiry No'=>'詢價編號','Invoice'=>'發票','Item Discount'=>'項目折扣','Items'=>'項目','Itinerary'=>'行程','Itinerary Map'=>'行程地圖','Language'=>'語言','Location'=>'地點','Locked'=>'鎖定','Main Experience'=>'主要體驗','Mark Done'=>'標記完成','Name'=>'名稱','Newest'=>'最新','Notes'=>'備註','Overdue'=>'逾期','Overview'=>'概覽','Paid At'=>'付款時間','Percent'=>'百分比','Permissions'=>'權限','Phone'=>'電話','Preview PDF'=>'預覽 PDF','Print'=>'列印','Print Detail'=>'列印詳情','Priority'=>'優先級','Provider'=>'供應商','Qty'=>'數量','Quick Actions'=>'快速操作','Quick Guide'=>'快速指南','Quotation'=>'報價單','Rate'=>'費率','Rates'=>'費率','Reason'=>'原因','Reason Note'=>'原因備註','Reject'=>'拒絕','Remaining approvals'=>'剩餘審批','Reminder Follow-up'=>'提醒跟進','Reply'=>'回覆','Reset'=>'重設','Role'=>'角色','Rooms'=>'房型','Rule'=>'規則','Save'=>'儲存','Schedule by Day'=>'按天行程','Service'=>'服務','Set Final'=>'設為最終','Set Pending'=>'設為待處理','Start'=>'開始','Start Point'=>'起點','Status'=>'狀態','Sub Total'=>'小計','Summary'=>'摘要','Switch Language'=>'切換語言','Symbol'=>'符號','Title'=>'標題','To Date'=>'結束日期','Total'=>'總計','Type'=>'類型','Unit'=>'單位','Unit Price'=>'單價','Unknown'=>'未知','Update Global Discount'=>'更新全域折扣','Updated at'=>'更新時間','Updated by'=>'更新者','Validated By'=>'驗證者','Validation'=>'驗證','Validity Date'=>'有效日期','Vendor'=>'供應商','View'=>'查看','View Detail'=>'查看詳情','You'=>'你',
    'No data available.'=>'目前沒有資料。','Refine your list quickly.'=>'快速篩選你的清單。',':size/page'=>':size/頁',
    'Manage activity data.'=>'管理活動資料。','Activities'=>'活動','Add Activity'=>'新增活動','Save Activity'=>'儲存活動','Update Activity'=>'更新活動','Create a new activity record.'=>'建立新的活動資料。','Update activity details.'=>'更新活動詳情。',
    'Hotels'=>'酒店','Room'=>'房型','Display By Day'=>'按天顯示','Itinerary Detail'=>'行程詳情','Review itinerary details.'=>'查看行程詳情。','Create Itinerary'=>'建立行程','Update Itinerary'=>'更新行程','Save Itinerary'=>'儲存行程',
  ],
  'zh_Hans' => [
    'Create New Password'=>'创建新密码','Reset Password'=>'重置密码','Welcome Back'=>'欢迎回来','Back to Sign In'=>'返回登录','Confirm New Password'=>'确认新密码','Email Address'=>'电子邮箱','Forgot Password?'=>'忘记密码？','Loading...'=>'加载中...','New Password'=>'新密码','Password'=>'密码','Remember me'=>'记住我','Send Reset Link'=>'发送重置链接','Sending Link...'=>'发送中...','Sign In'=>'登录','Signing In...'=>'登录中...','Update Password'=>'更新密码','Processing...'=>'处理中...','Forgot Password'=>'忘记密码','Login'=>'登录','Set New Password'=>'设置新密码',
    'Actions'=>'操作','Activate'=>'启用','Active'=>'启用','Activity Timeline'=>'活动时间轴','Add History'=>'新增记录','Add Reminder'=>'新增提醒','Adult'=>'成人','All Days'=>'全部天数','All Destinations'=>'全部目的地','All Status'=>'全部状态','All Types'=>'全部类型','All Vendors'=>'全部供应商','Amount'=>'金额','Approval'=>'审批','Approval Log'=>'审批记录','Approve'=>'批准','Assigned'=>'已指派','Audit Info'=>'审计信息','Back'=>'返回','Benefits'=>'优势','Booking'=>'预订','Booking Number'=>'预订编号','Cancel'=>'取消','Cancellation Policy'=>'取消政策','Capacity'=>'容量','Channel'=>'渠道','Child'=>'儿童','Clone'=>'复制','Close'=>'关闭','Communication History'=>'沟通记录','Confirm Reject'=>'确认拒绝','Contact At'=>'联系时间','Country'=>'国家','Created'=>'已创建','Created At'=>'创建时间','Created By'=>'创建者','Customer'=>'客户','Deactivate'=>'停用','Deadline'=>'截止日期','Default'=>'默认','Delete'=>'删除','Description'=>'说明','Destination'=>'目的地','Detail'=>'详情','Disabled'=>'停用','Discount'=>'折扣','Discount Type'=>'折扣类型','Discount Value'=>'折扣值','Done'=>'完成','Download PDF'=>'下载 PDF','Duplicate'=>'复制','Duration'=>'天数','Edit'=>'编辑','Enabled'=>'启用','End'=>'结束','End Point'=>'终点','Excludes'=>'不含','Filters'=>'筛选','Final Amount'=>'最终金额','Fixed'=>'固定','Follow-up'=>'跟进','From Date'=>'开始日期','Gallery'=>'图库','Generate Quotation'=>'生成报价单','Generated By'=>'生成者','Global Discount'=>'全局折扣','Guidelines'=>'指引','Inactive'=>'停用','Includes'=>'包含','Info'=>'信息','Inquiry'=>'询价','Inquiry No'=>'询价编号','Invoice'=>'发票','Item Discount'=>'项目折扣','Items'=>'项目','Itinerary'=>'行程','Itinerary Map'=>'行程地图','Language'=>'语言','Location'=>'地点','Locked'=>'锁定','Main Experience'=>'主要体验','Mark Done'=>'标记完成','Name'=>'名称','Newest'=>'最新','Notes'=>'备注','Overdue'=>'逾期','Overview'=>'概览','Paid At'=>'付款时间','Percent'=>'百分比','Permissions'=>'权限','Phone'=>'电话','Preview PDF'=>'预览 PDF','Print'=>'打印','Print Detail'=>'打印详情','Priority'=>'优先级','Provider'=>'供应商','Qty'=>'数量','Quick Actions'=>'快捷操作','Quick Guide'=>'快速指南','Quotation'=>'报价单','Rate'=>'费率','Rates'=>'费率','Reason'=>'原因','Reason Note'=>'原因备注','Reject'=>'拒绝','Remaining approvals'=>'剩余审批','Reminder Follow-up'=>'提醒跟进','Reply'=>'回复','Reset'=>'重置','Role'=>'角色','Rooms'=>'房型','Rule'=>'规则','Save'=>'保存','Schedule by Day'=>'按天行程','Service'=>'服务','Set Final'=>'设为最终','Set Pending'=>'设为待处理','Start'=>'开始','Start Point'=>'起点','Status'=>'状态','Sub Total'=>'小计','Summary'=>'摘要','Switch Language'=>'切换语言','Symbol'=>'符号','Title'=>'标题','To Date'=>'结束日期','Total'=>'总计','Type'=>'类型','Unit'=>'单位','Unit Price'=>'单价','Unknown'=>'未知','Update Global Discount'=>'更新全局折扣','Updated at'=>'更新时间','Updated by'=>'更新者','Validated By'=>'验证者','Validation'=>'验证','Validity Date'=>'有效日期','Vendor'=>'供应商','View'=>'查看','View Detail'=>'查看详情','You'=>'你',
    'No data available.'=>'暂无数据。','Refine your list quickly.'=>'快速筛选你的列表。',':size/page'=>':size/页',
    'Manage activity data.'=>'管理活动资料。','Activities'=>'活动','Add Activity'=>'新增活动','Save Activity'=>'保存活动','Update Activity'=>'更新活动','Create a new activity record.'=>'创建新的活动资料。','Update activity details.'=>'更新活动详情。',
    'Hotels'=>'酒店','Room'=>'房型','Display By Day'=>'按天显示','Itinerary Detail'=>'行程详情','Review itinerary details.'=>'查看行程详情。','Create Itinerary'=>'创建行程','Update Itinerary'=>'更新行程','Save Itinerary'=>'保存行程',
  ]
];

function exportArray(array $arr): string {
  $out = "<?php\n\nreturn [\n";
  foreach ($arr as $k => $v) {
    $ks = str_replace(["\\", "'"], ["\\\\", "\\'"], (string)$k);
    if (is_string($v)) {
      $vs = str_replace(["\\", "'"], ["\\\\", "\\'"], $v);
      $out .= "    '{$ks}' => '{$vs}',\n";
    } else {
      $out .= "    '{$ks}' => " . var_export($v, true) . ",\n";
    }
  }
  $out .= "];\n";
  return $out;
}

foreach($targets as $locale => $path){
  $arr = include $path;
  $dict = $maps[$locale];
  $count = 0;
  foreach($arr as $k => $v){
    if(!is_string($v) || $v === '') continue;
    if(isset($dict[$v])){
      $nv = $dict[$v];
      if($nv !== $v){
        $arr[$k] = $nv;
        $count++;
      }
    }
  }
  file_put_contents($path, exportArray($arr));
  echo "$locale patched=$count\n";
}
